import { NextRequest, NextResponse } from "next/server";
import { createServerClient } from "@supabase/ssr";
import { convertRecruiterLead } from "@/lib/leadService";

/**
 * /auth/callback — Server-side PKCE OAuth callback handler.
 *
 * WHY @supabase/ssr instead of createClient:
 * PKCE requires the code_verifier that was generated by the browser client when
 * signInWithOAuth was called. The browser client (flowType: "pkce") writes the
 * verifier to localStorage under the key `${storageKey}-code-verifier`.
 * However, with detectSessionInUrl:true the browser client ALSO mirrors the
 * verifier to a cookie of the same name so it survives cross-origin redirects.
 *
 * createClient on the server falls into memoryLocalStorageAdapter (an empty
 * in-process object) — no verifier → AuthPKCECodeVerifierMissingError → exchange fails.
 *
 * createServerClient from @supabase/ssr uses a cookie-based storage adapter that
 * reads/writes the verifier cookie from the incoming HTTP request, so
 * exchangeCodeForSession finds the verifier and succeeds.
 */

const IS_DEV = process.env.NODE_ENV !== "production";

function logAuthCallback(...args: any[]) {
  if (IS_DEV) {
    console.log("[HAQAuth:OAuthCallback]", ...args);
  }
}

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const code = searchParams.get("code");
  const roleParam = searchParams.get("role") || "candidate";
  const targetRole: "candidate" | "recruiter" =
    roleParam === "recruiter" ? "recruiter" : "candidate";

  const getRedirectPath = (role: string) =>
    role === "recruiter" ? "/dashboard/recruiter" : "/dashboard";

  logAuthCallback(
    "Processing OAuth callback. Code present:",
    !!code,
    "Target role from URL:",
    targetRole
  );

  if (!code) {
    logAuthCallback("Missing OAuth code. Redirecting to /login.");
    return NextResponse.redirect(new URL("/login?error=missing_code", request.url));
  }

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
  const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
  const isProduction = process.env.NODE_ENV === "production";

  // Build a response object to accumulate cookie writes
  const response = NextResponse.redirect(new URL("/login?error=auth_exchange_failed", request.url));

  try {
    // createServerClient uses a cookie-based storage adapter so the PKCE
    // code_verifier cookie (written by the browser client) is available
    // to _exchangeCodeForSession without needing localStorage.
    const supabaseServer = createServerClient(supabaseUrl, supabaseAnonKey, {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value, options }) => {
            response.cookies.set(name, value, {
              ...options,
              sameSite: "lax",
              secure: isProduction,
            });
          });
        },
      },
    });

    // Exchange the PKCE authorization code for a session.
    // createServerClient provides the code_verifier from the incoming cookie.
    const {
      data: { session },
      error: sessionError,
    } = await supabaseServer.auth.exchangeCodeForSession(code);

    if (sessionError || !session || !session.user) {
      console.error(
        "[HAQAuth:OAuthCallback] Session exchange error:",
        sessionError?.message
      );
      return NextResponse.redirect(
        new URL("/login?error=auth_exchange_failed", request.url)
      );
    }

    const user = session.user;
    logAuthCallback(
      "Code exchanged successfully. User ID:",
      user.id,
      "Email:",
      user.email
    );

    // After exchange, supabaseServer holds the active session.
    // Use it directly for subsequent profile lookups and metadata updates.

    // Check if a profile already exists (RLS allows authenticated read of own row)
    const { data: profile } = await supabaseServer
      .from("profiles")
      .select("*")
      .eq("id", user.id)
      .maybeSingle();

    let resolvedRole: "candidate" | "recruiter";

    if (profile) {
      // Existing user: DB profile role is always authoritative — never overwrite it.
      resolvedRole = profile.role === "recruiter" ? "recruiter" : "candidate";
      logAuthCallback(
        "Existing profile found. Preserving authoritative DB role:",
        resolvedRole
      );

      // Sync user_metadata.role if it drifted from the DB role
      if (user.user_metadata?.role !== resolvedRole) {
        try {
          await supabaseServer.auth.updateUser({ data: { role: resolvedRole } });
          logAuthCallback("Updated user_metadata.role to match DB role:", resolvedRole);
        } catch (metaErr) {
          console.error(
            "[HAQAuth:OAuthCallback] Failed to sync user metadata:",
            metaErr
          );
        }
      }
    } else {
      // First-time OAuth signup: create a profile with the portal's intended role
      resolvedRole = targetRole;
      logAuthCallback(
        "No existing profile found. Creating new profile with role:",
        resolvedRole
      );

      const fullName =
        user.user_metadata?.full_name ||
        user.user_metadata?.name ||
        "Google User";

      const { error: insertError } = await supabaseServer.from("profiles").insert({
        id: user.id,
        full_name: fullName,
        email: user.email || "",
        role: resolvedRole,
        company_name: user.user_metadata?.company_name || null,
        designation: user.user_metadata?.designation || null,
        created_at: new Date().toISOString(),
      });

      if (insertError) {
        console.error(
          "[HAQAuth:OAuthCallback] Profile insert error:",
          insertError.message
        );
      }

      // Write role into user_metadata for fast JWT reads by the proxy
      try {
        await supabaseServer.auth.updateUser({ data: { role: resolvedRole } });
      } catch (metaErr) {
        console.error(
          "[HAQAuth:OAuthCallback] Failed to update auth metadata:",
          metaErr
        );
      }

      // Link existing lead record if this is a recruiter signup
      if (resolvedRole === "recruiter" && user.email) {
        try {
          await convertRecruiterLead(user.email, user.id);
        } catch (leadErr) {
          console.error(
            "[HAQAuth:OAuthCallback] Failed to link recruiter lead:",
            leadErr
          );
        }
      }
    }

    // Detect portal mismatch (existing user who logged in on the wrong portal)
    const isRoleMismatch = !!profile && profile.role !== targetRole;
    if (isRoleMismatch) {
      logAuthCallback(
        `Role mismatch: User initiated OAuth on ${targetRole} portal ` +
          `but DB profile role is ${resolvedRole}. Routing directly to ${resolvedRole} dashboard.`
      );
    }

    const basePath = getRedirectPath(resolvedRole);
    const redirectPath = isRoleMismatch
      ? `${basePath}?notice=role_redirect`
      : basePath;

    logAuthCallback("Constructing redirect response to:", redirectPath);

    // Build the final redirect response.
    // createServerClient has already set Supabase's own session cookies via setAll().
    // Additionally write sb-access-token / sb-refresh-token for the proxy middleware
    // (proxy.ts reads these to validate the session at the edge without a DB call).
    const maxAge = session.expires_in || 3600;
    const finalResponse = NextResponse.redirect(
      new URL(redirectPath, request.url)
    );

    // Copy any Supabase SSR cookies already set on `response` → `finalResponse`
    response.cookies.getAll().forEach(({ name, value }) => {
      const options = response.cookies.get(name);
      finalResponse.cookies.set(name, value, {
        path: "/",
        sameSite: "lax",
        secure: isProduction,
        // Preserve the original max-age if the cookie already has one; otherwise use the session TTL
        maxAge: maxAge,
      });
    });

    // proxy.ts tokens — set explicitly so the edge middleware can read them
    finalResponse.cookies.set("sb-access-token", session.access_token, {
      path: "/",
      maxAge,
      sameSite: "lax",
      secure: isProduction,
    });

    if (session.refresh_token) {
      finalResponse.cookies.set("sb-refresh-token", session.refresh_token, {
        path: "/",
        maxAge: 604800,
        sameSite: "lax",
        secure: isProduction,
      });
    }

    logAuthCallback(
      "Session cookies set. Returning redirect response to:",
      redirectPath
    );
    return finalResponse;
  } catch (err: any) {
    console.error("[HAQAuth:OAuthCallback] Unexpected error:", err);
    return NextResponse.redirect(
      new URL(`/login?error=${encodeURIComponent(err.message)}`, request.url)
    );
  }
}
